blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path('/delete/<int:delete_id>', views.delete, name='delete'),
    path('/update/<int:update_id>', views.update, name='update'),
    path('/create', views.create, name='create'),
    path('/detail/<int:detail_id>', views.detail, name='detail'),
    path('/list', views.index),
]

coba_form/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog', include('blog.urls', namespace="blog")),
]

blog/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.
# memvalidasi di model krn yg ingin di validasi model (ini kl makenya model form yg di video kelas terbuka liat aja bedanya dahh)

def validate_author(value):
    judul_input = value
    if judul_input == "Einstein":
        message = "maaf" + judul_input + "tidak bisa diposting"
        raise ValidationError(message)


class PostModel(models.Model):
    Mata_Kuliah = models.CharField(max_length=100)
    Deskripsi = models.TextField(
        max_length=300,
        validators= [validate_author]
        )
    Dosen = models.CharField(max_length=100)
    Ruang_Kelas = models.CharField(max_length=100)
    Jumlah_SKS = models.CharField(max_length=100)

    LIST_SEMESTER = (
        ('Gasal 2020/2021', 'Gasal 2020/2021'),
        ('Genap 2020/2021', 'Genap 2020/2021'),
        ('Gasal 2019/2020', 'Gasal 2019/2020'),
        ('Genap 2019/2020', 'Genap 2019/2020'),
        ('Gasal 2018/2019', 'Gasal 2018/2019'),
        ('Genap 2018/2019', 'Genap 2018/2019'),
        ('Gasal 2017/2018', 'Gasal 2017/2018'),
        ('Genap 2017/2018', 'Genap 2017/2018'),
        )
    semester = models.CharField(
        max_length=100,
        choices= LIST_SEMESTER,
        default  = 'Maung',
    )
    published = models.DateTimeField(auto_now_add=True)
    


def __str__(self):
    return "{}.{}".format(self.id, self.judul)

blog/forms.py
from django import forms

#import model dari models.py
from .models import PostModel

class PostForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = [
            'Mata_Kuliah',
            'Deskripsi',
            'Dosen',
            'Ruang_Kelas',
            'Jumlah_SKS',
            'semester',
        ]
        widgets = {
            'Mata_Kuliah': forms.TextInput(  
                attrs={
                    'class' : 'form-control', #buat isi class sesuai bootstrapnya
                    'placeholder' : 'Mata kuliah',
                }
            ),

            'Deskripsi': forms.TextInput(  
                attrs={
                    'class' : 'form-control', #buat isi class sesuai bootstrapnya
                    'placeholder' : 'Deskripsi mengenai mata kuliah',
                }
            ),

            'Dosen': forms.TextInput(  
                attrs={
                    'class' : 'form-control', #buat isi class sesuai bootstrapnya
                    'placeholder' : 'nama dosen',
                }
            ),

            'Ruang_Kelas': forms.TextInput(  
                attrs={
                    'class' : 'form-control', #buat isi class sesuai bootstrapnya
                }
            ),

            'Jumlah_SKS': forms.TextInput(  
                attrs={
                    'class' : 'form-control', #buat isi class sesuai bootstrapnya
                }
            ),

            'semester': forms.Select(  
                attrs={
                    'class' : 'form-control', #buat isi class sesuai bootstrapnya
                }
            ),
        }

coba_form/forms.py
from django import forms

blog/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.
from .forms import PostForm
from .models import PostModel

def delete(request, delete_id):
    PostModel.objects.filter(id=delete_id).delete()
    return HttpResponseRedirect("/blog/list")

def update(request, update_id):
    akun_update = PostModel.objects.get(id=update_id)
    data = {
        'Mata_Kuliah' : akun_update.Mata_Kuliah,
        'Deskripsi': akun_update.Deskripsi,
        'Dosen' : akun_update.Dosen,
        'Ruang_Kelas' : akun_update.Ruang_Kelas,
        'Jumlah_SKS' : akun_update.Jumlah_SKS,
        'semester' : akun_update.semester,
    }
    post_form = PostForm(request.POST or None, initial=data, instance=akun_update)

    if request.method == 'POST':
        #cara ambil data dari input user ke database dg validasi
        if post_form.is_valid():
            post_form.save()
        return HttpResponseRedirect("/blog/list")

    
    context = {
        'pageTitle' : 'Update Form',
        'post_form' : post_form,
    }
    return render(request, 'blog/create.html', context)

def index(request):
    posts = PostModel.objects.all()
    context = {
        'heading' : 'Post',
        'contents': 'List Post',
        'posts' : posts,
    }
    return render(request, 'blog/list.html', context)

def create(request):
    post_form = PostForm(request.POST or None)
    if request.method == 'POST':
        #cara ambil data dari input user ke database dg validasi
        if post_form.is_valid():
            post_form.save()
        return HttpResponseRedirect("/blog/list")

    
    context = {
        'pageTitle' : 'Create Form',
        'post_form' : post_form,
    }
    return render(request, 'blog/create.html', context)

def detail(request, detail_id):
    akun = PostModel.objects.get(id=detail_id)
    akun_matkul = PostModel.objects.filter(id=detail_id)
    data = {
        'matkul' : akun_matkul
    }
    return render(request, 'blog/detail.html', data)

coba_form/views.py
from django.shortcuts import render

# Create your views here.
# from .forms import FormField

def index(request):
    return render(request, 'index.html')

blog/templates/blog/create.html
{% extends "base.html"%}
{% load static %}

{% block pageTitle %}
<section id="jumbo-index">
    <div class="jumbotron jumbotron-fluid">
      <div class="container " style="margin-top:20px;">
        <section name="form">
            <div class="container-fluid">
                <div class="container text-white" style="height: 670px;">
                    <h1>CREATE SCHEDULE</h1>
                    <form method = "POST" action="">
                        {% csrf_token %}
                        {% for a in post_form %}
                            <div class="form-group">
                                {{a.label}}
                                {{a}}
                            </div>
                        {% endfor %}
                        <button class="btn btn-primary" type="Submit">Kirim</button>
                    </form>
                </div>
              </div> 
            
        </section>
        <section id="social">
            <div class="container-fluid">
                <div class="row text-center">
                  <div class="col-12 social-menu">
                    <ul>
                      <li><a href="https://twitter.com/nadifaahsn"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="https://www.instagram.com/nadifahsn/?hl=en"><i class="fa fa-instagram"></i></a></li>
                      <li><a href="https://www.linkedin.com/in/hasna-nadifah-64635b1aa/"><i class="fa fa-linkedin"></i></a></li>
                      <li><a href="https://gitlab.com/nadifaahsn/"><i class="fa fa-github"></i></a></li>
                    </ul>
                  </div>
                </div>
              </div>
          </section>
      </div>
    </div>
</section>
<style>
    .btn {
        padding: 7px 30px;
        bottom: 20px;
        margin-right: 30px;
        outline: none;
        border: 1px solid whitesmoke;
        border-radius: 20px;
        cursor: pointer;
        color: whitesmoke;
        background: transparent;
    }
    #jumbo-index .jumbotron{
        background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url("/static/img/background.png");
        background-size: cover;
        background-position: center;
        height: 710px;
        width: 100%;
    }
    #social .social-menu ul{
        position: absolute;
        top: 50%;
        left: 50%;
        padding: 0;
        margin: 0;
        transform: translate(-50%, -50%);
        display: flex;
        margin-top: 35px;
        margin-bottom: 52px;
    }
    #social .social-menu ul li{
        list-style: none;
        margin: 0 15px;
    }
    #social .social-menu ul li .fa{
        font-size: 30px;
        line-height: 60px;
        transition: .6s;
        color: #000;
    }
    #social .social-menu ul li .fa:hover{
        color: #fff;
    }
    #social .social-menu ul li a{
        position: relative;
        display: block;
        width: 60px;
        height: 60px;
        border-radius: 50%;
        background-color: #fff;
        text-align: center;
        transition: .6s;
        box-shadow: 0 5px 4 px rgba(0,0,0,.5);
    }
    #social .social-menu ul li a:hover{
        transform: translate(0, -10px);
    }
    #social .social-menu ul li:nth-child(1) a:hover{
        background-color: #0077B5;
    }
    #social .social-menu ul li:nth-child(2) a:hover{
        background-color: #e4405f;
    }
    #social .social-menu ul li:nth-child(3) a:hover{
        background-color: #0084ff;
    }
    #social .social-menu ul li:nth-child(4) a:hover{
        background-color: #ff5700;
    }
</style>

{% endblock pageTitle %}

{% block contents%}

   
{% endblock contents%}

blog/templates/blog/detail.html
{% extends "base.html"%}
{% load static %}

{% block Title%}
    {{heading}}
{% endblock Title%}

{% block pageTitle %}
    <section id="jumbo-index">
        <div class="jumbotron jumbotron-fluid">
            <div class="container"> 
                <div class="container-fluid" style="margin-top: 30px;">
                    <div class="container text-white" style="height: 660px;">
                        <h1>SCHEDULE DETAIL</h1>
                        <table class="table">
                            <thead class="table  text-white text-center">
                                <th scope="col">Mata Kuliah</th>
                                <th scope="col">Deskripsi</th>
                                <th scope="col">Dosen</th>
                                <th scope="col">Ruang Kelas</th>
                                <th scope="col">Jumlah SKS</th>
                                <th scope="col">Semester</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </thead>
                            <tbody>
                                {% for a in matkul %}
                                <tr class="table text-white text-center">
                                    <td> {{a.Mata_Kuliah}} </td>
                                    <td> {{a.Deskripsi}} </td>
                                    <td> {{a.Dosen}} </td>
                                    <td> {{a.Ruang_Kelas}} </td>
                                    <td> {{a.Jumlah_SKS}} </td>
                                    <td> {{a.semester}} </td>
                                    <td><a class="btn btn-danger" href="{% url 'blog:delete' a.id %}">Delete</a></td>
                                    <td><a class="btn btn-warning" href="{% url 'blog:update' a.id %}">Update</a></td>
                                </tr> 
                                {% endfor %}
                            </tbody>
                        </table>
                        <a class="btn btn-primary" href="{% url 'blog:create'%}">Add</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="social">
    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-12 social-menu">
            <ul>
                <li><a href="https://twitter.com/nadifaahsn"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://www.instagram.com/nadifahsn/?hl=en"><i class="fa fa-instagram"></i></a></li>
                <li><a href="https://www.linkedin.com/in/hasna-nadifah-64635b1aa/"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="https://gitlab.com/nadifaahsn/"><i class="fa fa-github"></i></a></li>
            </ul>
            </div>
        </div>
        </div>
    </section>
  <style>
    #jumbo-index .jumbotron{
        background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url("/static/img/background.png");
        background-size: cover;
        background-position: center;
        height: 650px;
        width: 100%;
    }
    #social .social-menu ul{
        position: absolute;
        top: 50%;
        left: 50%;
        padding: 0;
        margin: 0;
        transform: translate(-50%, -50%);
        display: flex;
        margin-top: 50px;
        margin-bottom: 50px;
    }
    #social .social-menu ul li{
        list-style: none;
        margin: 0 15px;
    }
    #social .social-menu ul li .fa{
        font-size: 30px;
        line-height: 60px;
        transition: .6s;
        color: #000;
    }
    #social .social-menu ul li .fa:hover{
        color: #fff;
    }
    #social .social-menu ul li a{
        position: relative;
        display: block;
        width: 60px;
        height: 60px;
        border-radius: 50%;
        background-color: #fff;
        text-align: center;
        transition: .6s;
        box-shadow: 0 5px 4 px rgba(0,0,0,.5);
    }
    #social .social-menu ul li a:hover{
        transform: translate(0, -10px);
    }
    #social .social-menu ul li:nth-child(1) a:hover{
        background-color: #0077B5;
    }
    #social .social-menu ul li:nth-child(2) a:hover{
        background-color: #e4405f;
    }
    #social .social-menu ul li:nth-child(3) a:hover{
        background-color: #0084ff;
    }
    #social .social-menu ul li:nth-child(4) a:hover{
        background-color: #ff5700;
    }
  </style>
{% endblock pageTitle%}

blog/templates/blog/list.html
{% extends "base.html"%}
{% load static %}

{% block Title%}
    {{heading}}
{% endblock Title%}

{% block pageTitle %}
    <section id="jumbo-index">
        <div class="jumbotron jumbotron-fluid">
            <div class="container"> 
                <div class="container-fluid" style="margin-top: 30px;">
                    <div class="container text-white" style="height: 660px;">
                        <h1>SCHEDULE</h1>
                        <table class="table">
                            <thead class="table  text-white text-center">
                                <th scope="col">Mata Kuliah</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </thead>
                            <tbody>
                                {% for a in posts %}
                                <tr class="table text-white text-center">
                                    <td><a class="text-white" href="{% url 'blog:detail' a.id%}"> {{a.Mata_Kuliah}} </a></td>
                                    <td><a class="btn btn-light" href="{% url 'blog:detail' a.id %}">Detail</a></td>
                                    <td><a class="btn btn-danger" href="{% url 'blog:delete' a.id %}">Delete</a></td>
                                    <td><a class="btn btn-warning" href="{% url 'blog:update' a.id %}">Update</a></td>
                                </tr> 
                                {% endfor %}
                            </tbody>
                        </table>
                        <a class="btn btn-primary" href="{% url 'blog:create'%}">Add</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="social">
    <div class="container-fluid">
        <div class="row text-center">
            <div class="col-12 social-menu">
            <ul>
                <li><a href="https://twitter.com/nadifaahsn"><i class="fa fa-twitter"></i></a></li>
                <li><a href="https://www.instagram.com/nadifahsn/?hl=en"><i class="fa fa-instagram"></i></a></li>
                <li><a href="https://www.linkedin.com/in/hasna-nadifah-64635b1aa/"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="https://gitlab.com/nadifaahsn/"><i class="fa fa-github"></i></a></li>
            </ul>
            </div>
        </div>
        </div>
    </section>
  <style>
    #jumbo-index .jumbotron{
        background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url("/static/img/background.png");
        background-size: cover;
        background-position: center;
        height: 650px;
        width: 100%;
    }
    #social .social-menu ul{
        position: absolute;
        top: 50%;
        left: 50%;
        padding: 0;
        margin: 0;
        transform: translate(-50%, -50%);
        display: flex;
        margin-top: 50px;
        margin-bottom: 50px;
    }
    #social .social-menu ul li{
        list-style: none;
        margin: 0 15px;
    }
    #social .social-menu ul li .fa{
        font-size: 30px;
        line-height: 60px;
        transition: .6s;
        color: #000;
    }
    #social .social-menu ul li .fa:hover{
        color: #fff;
    }
    #social .social-menu ul li a{
        position: relative;
        display: block;
        width: 60px;
        height: 60px;
        border-radius: 50%;
        background-color: #fff;
        text-align: center;
        transition: .6s;
        box-shadow: 0 5px 4 px rgba(0,0,0,.5);
    }
    #social .social-menu ul li a:hover{
        transform: translate(0, -10px);
    }
    #social .social-menu ul li:nth-child(1) a:hover{
        background-color: #0077B5;
    }
    #social .social-menu ul li:nth-child(2) a:hover{
        background-color: #e4405f;
    }
    #social .social-menu ul li:nth-child(3) a:hover{
        background-color: #0084ff;
    }
    #social .social-menu ul li:nth-child(4) a:hover{
        background-color: #ff5700;
    }
  </style>
{% endblock pageTitle%}

{% block contents%}


    <!-- <h1>{{contents}}</h1>
    {% for a in posts %}
        <h2>{{a.judul}}</h2>
        <h3>penulis: {{a.author}}</h3>
        <h3>category: {{a.category}}</h3>
        <p>{{a.body}}</p>
    {% endfor %} -->
{% endblock contents%}

<!-- <style>
    table, th, td {
       border: 1px solid black;
       border-collapse: collapse;
   }
</style>
<table align="center" style="text-align: center" "width:100%">
    {% for a in posts %}
    <tr>
        <td>{{a.judul}}</td>
        <td>penulis: {{a.author}}</td>
        <td>category: {{a.category}}</td>
        <td>{{a.body}}</td>
    </tr>
{% endfor %}
</table> -->

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>
        {% block Title%}
         
        {% endblock Title%}
    </title>
</head>
<body>
  <nav class="navbar fixed-top navbar-expand-md navbar-dark" id="myNav">
    <a class="navbar-brand" href="/">Form</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="/" title="">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="/schedule" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Blog
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/blog/create">Create</a>
            <a class="dropdown-item" href="/blog/list">Result</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin" title="">Admin</a>
        </li>
      </ul>
    </div>
  </nav>

    
  {% block pageTitle %}

  {% endblock pageTitle%}
   
  
  {% block contents%}

  {% endblock contents%}
      

  
    
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
</body>

  
</html>

templates/index.html
{% extends "base.html"%}
{% load static%}

{% block Title%}
    {{heading}}
{% endblock Title%}

{% block pageTitle %}
<section id="jumbo-index">
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4 text-white " style="margin-top: 160px;">W E L C O M E<br>T O  &nbsp;S C H E D U L E  &nbsp;M A K E R</h1>
        <a href="/blog/create">TRY TO MAKE!</a>
      </div>
    </div>
</section>
<section id="social">
  <div class="container-fluid">
      <div class="row text-center">
        <div class="col-12 social-menu">
          <ul>
            <li><a href="https://twitter.com/nadifaahsn"><i class="fa fa-twitter"></i></a></li>
            <li><a href="https://www.instagram.com/nadifahsn/?hl=en"><i class="fa fa-instagram"></i></a></li>
            <li><a href="https://www.linkedin.com/in/hasna-nadifah-64635b1aa/"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="https://gitlab.com/nadifaahsn/"><i class="fa fa-github"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
</section>
  <style>
    #jumbo-index .jumbotron{
        background-image: linear-gradient(rgba(0,0,0,0.7), rgba(0,0,0,0.7)), url("/static/img/background.png");
        background-size: cover;
        background-position: center;
        height: 650px;
        width: 100%;
    }
    #jumbo-index a{
        display: inline-block;
        margin-top: 20px;
        padding: 8px 20px;
        background: #fff;
        color: #111;
        border-radius: 40px;
        font-weight: 500;
        letter-spacing: 1px;
        text-decoration: none;
        text-transform: uppercase;
    }
    #social .social-menu ul{
        position: absolute;
        top: 50%;
        left: 50%;
        padding: 0;
        margin: 0;
        transform: translate(-50%, -50%);
        display: flex;
        margin-top: 70px;
        margin-bottom: 50px;
    }
    #social .social-menu ul li{
        list-style: none;
        margin: 0 15px;
    }
    #social .social-menu ul li .fa{
        font-size: 30px;
        line-height: 60px;
        transition: .6s;
        color: #000;
    }
    #social .social-menu ul li .fa:hover{
        color: #fff;
    }
    #social .social-menu ul li a{
        position: relative;
        display: block;
        width: 60px;
        height: 60px;
        border-radius: 50%;
        background-color: #fff;
        text-align: center;
        transition: .6s;
        box-shadow: 0 5px 4 px rgba(0,0,0,.5);
    }
    #social .social-menu ul li a:hover{
        transform: translate(0, -10px);
    }
    #social .social-menu ul li:nth-child(1) a:hover{
        background-color: #0077B5;
    }
    #social .social-menu ul li:nth-child(2) a:hover{
        background-color: #e4405f;
    }
    #social .social-menu ul li:nth-child(3) a:hover{
        background-color: #0084ff;
    }
    #social .social-menu ul li:nth-child(4) a:hover{
        background-color: #ff5700;
    }
  </style>
{% endblock pageTitle%}

{% block contents%}

{% endblock contents%}
















<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{heading}}t</title>
</head>
<body>
    <h1>{{heading}}</h1>

    <ul>
        <li><a href="{% url 'index' %}"></a></li>
        <li><a href="/contact">contact</a></li>
    </ul>
    <form methos= 'POST' action="">
        {% csrf_token %}
        <table>
            {{data_form.as_table}}
        </table>
        <br>
        <button type="Submit">Kirim</button>
    </form>
</body>
</html> -->